# Tables and a bit-exact reference for the 3D renderer with animated face turns.
# Run directly to regenerate render3d_data.s.
import math, os, sys
HERE = os.path.dirname(os.path.abspath(__file__))

POS = {0:(-1,1,1),1:(1,1,1),2:(1,-1,1),3:(-1,-1,1),4:(1,1,-1),5:(1,-1,-1),6:(-1,-1,-1),7:(-1,1,-1)}
def sd(p, ax):
    v = [0,0,0]; v[ax] = POS[p][ax]; return tuple(v)
def cyc(p):   # sticker slot order of a position, as verified in render/model.py
    a = sd(p,1); b = sd(p,2); c = sd(p,0)
    det = a[0]*(b[1]*c[2]-b[2]*c[1]) - a[1]*(b[0]*c[2]-b[2]*c[0]) + a[2]*(b[0]*c[1]-b[1]*c[0])
    o = [1,2,0] if det < 0 else [1,0,2]
    return [o[0], o[2], o[1]]

NSTEP = 32
SIN = [round(256*math.sin(2*math.pi*i/NSTEP)) for i in range(NSTEP)]
CPHI = round(256*math.cos(math.radians(30))); SPHI = round(256*math.sin(math.radians(30)))
CX = 17*256 + 128; CY = 12*256 + 128
CAM_YAW = 28                       # -45 degrees: U, F and R face the viewer
SAMPLES = 8                        # samples per edge of one sticker
# moves 0..8: R R2 R' B B2 B' D D2 D'
# axis of the face, coordinate of the turning layer on that axis,
# angle step per frame (clockwise seen from outside), number of frames
FACE_AXIS = [0, 2, 1]
FACE_LAYER = [1, -1, -1]
FACE_SENSE = [-1, 1, 1]            # rotation by -90 deg about the outward normal
def move_params(m):
    f, q = m // 3, m % 3
    turns = {0: 1, 1: 2, 2: -1}[q]
    step = FACE_SENSE[f] * (1 if turns > 0 else -1)
    return FACE_AXIS[f], FACE_LAYER[f], step, 8 * abs(turns)

def fmul(a, b):
    s = -1 if (a < 0) != (b < 0) else 1
    return s * ((abs(a) * abs(b)) >> 8)
def sincos(i):
    return SIN[i % NSTEP], SIN[(i + 8) % NSTEP]
def camera(yaw):
    s, c = sincos(yaw)
    return [[c, 0, s], [fmul(SPHI, s), CPHI, -fmul(SPHI, c)], [-fmul(CPHI, s), SPHI, fmul(CPHI, c)]]
def layer(axis, angle):
    s, c = sincos(angle)
    L = [[256,0,0],[0,256,0],[0,0,256]]
    if axis == 0:   L[1][1], L[1][2], L[2][1], L[2][2] = c, -s, s, c
    elif axis == 1: L[0][0], L[0][2], L[2][0], L[2][2] = c, s, -s, c
    else:           L[0][0], L[0][1], L[1][0], L[1][1] = c, -s, s, c
    return L
def matmul(A, B):
    return [[sum(fmul(A[i][k], B[k][j]) for k in range(3)) for j in range(3)] for i in range(3)]
def h(v):  return (v << 1) + v + (v >> 1)       # 3.5 v
def f7(v): return (v << 3) - v                  # 7 v
def asr(v, n): return v >> n

def draw(M, colors, move=None, angle=0):
    """M: camera matrix; colors[p*3+slot]; move/angle: the layer being turned."""
    T = None
    if move is not None:
        ax, lay, _, _ = move_params(move)
        T = matmul(M, layer(ax, angle))
    fb = [0]*875; zb = [-2**31]*875
    for p in range(8):
        P = POS[p]
        G = T if (T is not None and P[ax] == lay) else M
        hc = [[h(G[i][j]) for i in range(3)] for j in range(3)]    # hc[j] = 3.5 * column j
        fc = [[f7(G[i][j]) for i in range(3)] for j in range(3)]   # fc[j] = 7 * column j
        C = [sum(hc[j][i] if P[j] > 0 else -hc[j][i] for j in range(3)) for i in range(3)]
        for a in range(3):
            u, v = (a + 1) % 3, (a + 2) % 3
            for s in (1, -1):
                nz = G[2][a] if s > 0 else -G[2][a]
                if nz <= 0: continue
                O = [C[i] + (hc[a][i] if s > 0 else -hc[a][i]) - hc[u][i] - hc[v][i] for i in range(3)]
                d1 = [asr(fc[u][i], 3) for i in range(3)]
                d2 = [asr(fc[v][i], 3) for i in range(3)]
                col = colors[p*3 + cyc(p).index(a)] if P[a] == s else 0
                rx = CX + O[0] + asr(d1[0],1) + asr(d2[0],1)
                ry = CY - (O[1] + asr(d1[1],1) + asr(d2[1],1))
                rz = O[2] + asr(d1[2],1) + asr(d2[2],1)
                for b in range(SAMPLES):
                    x, y, z = rx, ry, rz
                    for _ in range(SAMPLES):
                        px, py = asr(x, 8), asr(y, 8)
                        if 0 <= px < 35 and 0 <= py < 25:
                            k = py*35 + px
                            if z > zb[k]:
                                zb[k] = z; fb[k] = col
                        x += d1[0]; y -= d1[1]; z += d1[2]
                    rx += d2[0]; ry -= d2[1]; rz += d2[2]
    return fb

def write_tables():
    out = ["# Generated by render3d/gen3d.py: tables for the 3D renderer.",
           "    .data", "    .align 2",
           "sin_q8:                      # sin(2 pi i / 32) in Q8, i = 0..31",
           "    .half " + ", ".join(map(str, SIN[:16])),
           "    .half " + ", ".join(map(str, SIN[16:])),
           "pos_xyz:                     # corner position p -> (x, y, z), each +1 or -1",
           ]
    for p in range(8): out.append("    .byte %d, %d, %d" % POS[p])
    out.append("pos_slot:                    # [p][axis] -> sticker slot of that axis (cyc order)")
    for p in range(8): out.append("    .byte %d, %d, %d" % tuple(cyc(p).index(a) for a in range(3)))
    out.append("move_anim:                   # move -> axis, layer coordinate, angle step per frame, frames")
    for m in range(9): out.append("    .byte %d, %d, %d, %d" % move_params(m))
    out.append("    .align 2")
    open(os.path.join(HERE, 'render3d_data.s'), 'w').write("\n".join(out) + "\n")

if __name__ == "__main__":
    write_tables()
    print("camera", camera(CAM_YAW))
