# Generated by render3d/gen3d.py: tables for the 3D renderer.
    .data
    .align 2
sin_q8:                      # sin(2 pi i / 32) in Q8, i = 0..31
    .half 0, 50, 98, 142, 181, 213, 237, 251, 256, 251, 237, 213, 181, 142, 98, 50
    .half 0, -50, -98, -142, -181, -213, -237, -251, -256, -251, -237, -213, -181, -142, -98, -50
pos_xyz:                     # corner position p -> (x, y, z), each +1 or -1
    .byte -1, 1, 1
    .byte 1, 1, 1
    .byte 1, -1, 1
    .byte -1, -1, 1
    .byte 1, 1, -1
    .byte 1, -1, -1
    .byte -1, -1, -1
    .byte -1, 1, -1
pos_slot:                    # [p][axis] -> sticker slot of that axis (cyc order)
    .byte 1, 0, 2
    .byte 2, 0, 1
    .byte 1, 0, 2
    .byte 2, 0, 1
    .byte 1, 0, 2
    .byte 2, 0, 1
    .byte 1, 0, 2
    .byte 2, 0, 1
move_anim:                   # move -> axis, layer coordinate, angle step per frame, frames
    .byte 0, 1, -1, 8
    .byte 0, 1, -1, 16
    .byte 0, 1, 1, 8
    .byte 2, -1, 1, 8
    .byte 2, -1, 1, 16
    .byte 2, -1, -1, 8
    .byte 1, -1, 1, 8
    .byte 1, -1, 1, 16
    .byte 1, -1, -1, 8
    .align 2

    .equ CPHI, 222           # cos 30 degrees in Q8 (camera pitch)
    .equ SPHI, 128           # sin 30 degrees in Q8
    .equ CX, 4480            # screen centre x = 17.5 in Q8
    .equ CY, 3200            # screen centre y = 12.5 in Q8
cam:
    .zero 36                 # camera matrix, Q8, row-major M[i][j] at (3i + j) * 4
lmat:
    .zero 36                 # rotation of the turning layer
tmat:
    .zero 36                 # cam * lmat, used for the cubies of the turning layer
hcol:
    .zero 36                 # 3.5 * column j of the current matrix, at (3j + i) * 4
fcol:
    .zero 36                 # 7 * column j
rowv:
    .zero 24                 # current row start (x, y, z) and row step (x, -y, z)
colors:
    .zero 96                 # RGB of each facelet, index position * 3 + slot
fbz:
    .zero 7000               # per pixel: colour, depth (frame buffer and z-buffer)

    .text
# ---------------------------------------------------------------------------
# fmul: a0 = (a0 * a1) >> 8 for signed Q8 values, by shift and add
# (RV32I has no multiply, and __mulsi3 is not allowed). Uses t0-t2.
# ---------------------------------------------------------------------------
fmul:
    xor  t2, a0, a1          # bit 31 of t2 = sign of the product
    bgez a0, fm_a
    neg  a0, a0
fm_a:
    bgez a1, fm_b
    neg  a1, a1
fm_b:
    li   t0, 0
fm_loop:
    beqz a1, fm_done
    andi t1, a1, 1
    beqz t1, fm_skip
    add  t0, t0, a0          # add the shifted multiplicand for each 1 bit
fm_skip:
    slli a0, a0, 1
    srli a1, a1, 1
    j    fm_loop
fm_done:
    srli a0, t0, 8           # back to Q8
    bgez t2, fm_ret
    neg  a0, a0
fm_ret:
    ret

# ---------------------------------------------------------------------------
# sincos: a0 = angle step (any integer, taken mod 32) -> a0 = sin, a1 = cos (Q8)
# ---------------------------------------------------------------------------
sincos:
    la   t0, sin_q8
    andi t1, a0, 31
    slli t1, t1, 1
    add  t1, t0, t1
    addi a1, a0, 8           # cos(x) = sin(x + 90 degrees)
    andi a1, a1, 31
    slli a1, a1, 1
    add  a1, t0, a1
    lh   a0, 0(t1)
    lh   a1, 0(a1)
    ret

# ---------------------------------------------------------------------------
# build_camera: a0 = yaw step -> cam = Rx(30 degrees) * Ry(yaw)
#   [[c, 0, s], [sphi s, cphi, -sphi c], [-cphi s, sphi, cphi c]]
# ---------------------------------------------------------------------------
build_camera:
    addi sp, sp, -16
    sw   ra, 0(sp)
    sw   s0, 4(sp)
    sw   s1, 8(sp)
    sw   s2, 12(sp)
    jal  ra, sincos
    mv   s0, a0              # s
    mv   s1, a1              # c
    la   s2, cam
    sw   s1, 0(s2)
    sw   zero, 4(s2)
    sw   s0, 8(s2)
    li   a0, SPHI
    mv   a1, s0
    jal  ra, fmul
    sw   a0, 12(s2)
    li   t0, CPHI
    sw   t0, 16(s2)
    li   a0, SPHI
    mv   a1, s1
    jal  ra, fmul
    neg  a0, a0
    sw   a0, 20(s2)
    li   a0, CPHI
    mv   a1, s0
    jal  ra, fmul
    neg  a0, a0
    sw   a0, 24(s2)
    li   t0, SPHI
    sw   t0, 28(s2)
    li   a0, CPHI
    mv   a1, s1
    jal  ra, fmul
    sw   a0, 32(s2)
    lw   ra, 0(sp)
    lw   s0, 4(sp)
    lw   s1, 8(sp)
    lw   s2, 12(sp)
    addi sp, sp, 16
    ret

# ---------------------------------------------------------------------------
# build_layer: a0 = axis (0 x, 1 y, 2 z), a1 = angle step -> lmat = rotation
# of the turning layer about that axis.
# ---------------------------------------------------------------------------
build_layer:
    addi sp, sp, -8
    sw   ra, 0(sp)
    sw   s0, 4(sp)
    mv   s0, a0
    mv   a0, a1
    jal  ra, sincos          # a0 = s, a1 = c
    la   t0, lmat            # start from the identity
    li   t1, 256
    sw   t1, 0(t0)
    sw   zero, 4(t0)
    sw   zero, 8(t0)
    sw   zero, 12(t0)
    sw   t1, 16(t0)
    sw   zero, 20(t0)
    sw   zero, 24(t0)
    sw   zero, 28(t0)
    sw   t1, 32(t0)
    neg  t2, a0              # t2 = -s
    beqz s0, bl_x
    li   t1, 1
    beq  s0, t1, bl_y
    sw   a1, 0(t0)           # z: [[c, -s, 0], [s, c, 0], [0, 0, 1]]
    sw   t2, 4(t0)
    sw   a0, 12(t0)
    sw   a1, 16(t0)
    j    bl_done
bl_x:
    sw   a1, 16(t0)          # x: [[1, 0, 0], [0, c, -s], [0, s, c]]
    sw   t2, 20(t0)
    sw   a0, 28(t0)
    sw   a1, 32(t0)
    j    bl_done
bl_y:
    sw   a1, 0(t0)           # y: [[c, 0, s], [0, 1, 0], [-s, 0, c]]
    sw   a0, 8(t0)
    sw   t2, 24(t0)
    sw   a1, 32(t0)
bl_done:
    lw   ra, 0(sp)
    lw   s0, 4(sp)
    addi sp, sp, 8
    ret

# ---------------------------------------------------------------------------
# matmul3: tmat = cam * lmat, each product with fmul.
# ---------------------------------------------------------------------------
matmul3:
    addi sp, sp, -24
    sw   ra, 0(sp)
    sw   s0, 4(sp)
    sw   s1, 8(sp)
    sw   s2, 12(sp)
    sw   s3, 16(sp)
    sw   s4, 20(sp)
    li   s0, 0               # i
mm_i:
    li   s1, 0               # j
mm_j:
    li   s3, 0               # sum
    li   s2, 0               # k
mm_k:
    slli t3, s0, 1           # cam[i][k]
    add  t3, t3, s0
    add  t3, t3, s2
    slli t3, t3, 2
    la   t4, cam
    add  t3, t4, t3
    lw   a0, 0(t3)
    slli t3, s2, 1           # lmat[k][j]
    add  t3, t3, s2
    add  t3, t3, s1
    slli t3, t3, 2
    la   t4, lmat
    add  t3, t4, t3
    lw   a1, 0(t3)
    jal  ra, fmul
    add  s3, s3, a0
    addi s2, s2, 1
    li   t3, 3
    bne  s2, t3, mm_k
    slli t3, s0, 1           # tmat[i][j] = sum
    add  t3, t3, s0
    add  t3, t3, s1
    slli t3, t3, 2
    la   t4, tmat
    add  t3, t4, t3
    sw   s3, 0(t3)
    addi s1, s1, 1
    li   t3, 3
    bne  s1, t3, mm_j
    addi s0, s0, 1
    bne  s0, t3, mm_i
    lw   ra, 0(sp)
    lw   s0, 4(sp)
    lw   s1, 8(sp)
    lw   s2, 12(sp)
    lw   s3, 16(sp)
    lw   s4, 20(sp)
    addi sp, sp, 24
    ret

# ---------------------------------------------------------------------------
# compute_colors: colors[position * 3 + slot] from cube_p / cube_o,
# with the same rule as render_cube. Uses t1-t5, a0-a6.
# ---------------------------------------------------------------------------
compute_colors:
    la   t1, colors
    la   t2, cubie_color
    la   t3, cube_p
    la   t4, cube_o
    li   t5, 0
cc_pos:
    beqz t5, cc_anchor
    add  a0, t3, t5
    lbu  a1, -1(a0)
    addi a1, a1, 1
    add  a0, t4, t5
    lbu  a2, -1(a0)
    j    cc_have
cc_anchor:
    li   a1, 0
    li   a2, 0
cc_have:
    slli a3, a1, 3           # cubie_color + 12 * c
    slli a4, a1, 2
    add  a3, a3, a4
    add  a3, t2, a3
    li   a4, 0
cc_slot:
    sub  a5, a4, a2          # (k - o) mod 3
    bgez a5, cc_j
    addi a5, a5, 3
cc_j:
    slli a5, a5, 2
    add  a5, a3, a5
    lw   a6, 0(a5)
    sw   a6, 0(t1)
    addi t1, t1, 4
    addi a4, a4, 1
    li   a5, 3
    bne  a4, a5, cc_slot
    addi t5, t5, 1
    li   a5, 8
    bne  t5, a5, cc_pos
    ret

# ---------------------------------------------------------------------------
# draw_cubies: a0 = move being animated (-1: none), a1 = its angle step.
#
# The cube is drawn as eight cubies of edge 7 pixels. Cubies of the turning
# layer use tmat = cam * lmat, the others use cam. A cubie's faces are axis
# aligned, so the image of each face is built from the columns of its matrix
# scaled by 3.5 (half edge) and 7 (edge): shifts and adds only. Each face that
# points at the viewer is sampled on an 8 x 8 grid with constant steps, and a
# depth buffer keeps the nearest sample per pixel. Outer faces carry their
# sticker colour; inner faces are black and show the gaps of a turning layer.
# ---------------------------------------------------------------------------
draw_cubies:
    addi sp, sp, -52
    sw   ra, 0(sp)
    sw   s0, 4(sp)
    sw   s1, 8(sp)
    sw   s2, 12(sp)
    sw   s3, 16(sp)
    sw   s4, 20(sp)
    sw   s5, 24(sp)
    sw   s6, 28(sp)
    sw   s7, 32(sp)
    sw   s8, 36(sp)
    sw   s9, 40(sp)
    sw   s10, 44(sp)
    sw   s11, 48(sp)

    li   s10, -1             # s10 = axis of the turning layer, -1 if none
    bltz a0, dc_clear
    la   t0, move_anim
    slli t1, a0, 2
    add  t0, t0, t1
    lb   s10, 0(t0)          # axis
    lb   s9, 1(t0)           # s9 = coordinate of the turning layer on that axis
    mv   a0, s10
    jal  ra, build_layer     # a1 = angle is still in a1
    jal  ra, matmul3

dc_clear:
    la   t0, fbz             # colour 0, depth -infinity
    lui  t1, 0x80000
    li   t2, 875
dc_clr:
    sw   zero, 0(t0)
    sw   t1, 4(t0)
    addi t0, t0, 8
    addi t2, t2, -1
    bnez t2, dc_clr

    li   s0, 0               # s0 = position p
    la   s1, pos_xyz         # s1 = &pos_xyz[p][0]
dc_cubie:
    la   s2, cam             # s2 = matrix of this cubie
    bltz s10, dc_mat
    add  t0, s1, s10
    lb   t0, 0(t0)
    bne  t0, s9, dc_mat
    la   s2, tmat
dc_mat:
    li   t2, 0               # hcol[j][i] = 3.5 G[i][j], fcol[j][i] = 7 G[i][j]
dc_hj:
    li   t3, 0
dc_hi:
    slli t4, t3, 1
    add  t4, t4, t3
    add  t4, t4, t2
    slli t4, t4, 2
    add  t4, s2, t4
    lw   t5, 0(t4)           # G[i][j]
    slli t6, t2, 1
    add  t6, t6, t2
    add  t6, t6, t3
    slli t6, t6, 2           # (3j + i) * 4
    slli a0, t5, 1           # 3.5 g = 2g + g + g/2
    add  a0, a0, t5
    srai a1, t5, 1
    add  a0, a0, a1
    la   a1, hcol
    add  a1, a1, t6
    sw   a0, 0(a1)
    slli a0, t5, 3           # 7 g = 8g - g
    sub  a0, a0, t5
    la   a1, fcol
    add  a1, a1, t6
    sw   a0, 0(a1)
    addi t3, t3, 1
    li   a0, 3
    bne  t3, a0, dc_hi
    addi t2, t2, 1
    bne  t2, a0, dc_hj

    li   s3, 0               # (s3, s4, s5) = cubie centre = sum of +-3.5 columns
    li   s4, 0
    li   s5, 0
    la   t0, hcol
    li   t2, 0
dc_cj:
    add  t1, s1, t2
    lb   t1, 0(t1)
    lw   t3, 0(t0)
    lw   t4, 4(t0)
    lw   t5, 8(t0)
    bltz t1, dc_cneg
    add  s3, s3, t3
    add  s4, s4, t4
    add  s5, s5, t5
    j    dc_cnext
dc_cneg:
    sub  s3, s3, t3
    sub  s4, s4, t4
    sub  s5, s5, t5
dc_cnext:
    addi t0, t0, 12
    addi t2, t2, 1
    li   t1, 3
    bne  t2, t1, dc_cj

    li   s6, 0               # s6 = face axis a
dc_axis:
    li   s7, 1               # s7 = side +1, then -1
dc_side:
    slli t0, s6, 2           # depth of the normal: side * G[2][a]
    add  t0, s2, t0
    lw   t0, 24(t0)
    bgtz s7, dc_nz
    neg  t0, t0
dc_nz:
    blez t0, dc_side_next    # facing away

    li   t2, 3               # u = (a + 1) mod 3, v = (a + 2) mod 3
    addi t1, s6, 1
    blt  t1, t2, dc_u
    addi t1, t1, -3
dc_u:
    addi t3, s6, 2
    blt  t3, t2, dc_v
    addi t3, t3, -3
dc_v:
    slli t4, t1, 3           # offsets * 12
    slli t1, t1, 2
    add  t1, t1, t4
    slli t4, t3, 3
    slli t3, t3, 2
    add  t3, t3, t4
    slli t4, s6, 3
    slli t5, s6, 2
    add  t5, t5, t4
    la   t0, hcol
    add  a2, t0, t5          # a2 = &hcol[a]
    add  a3, t0, t1          # a3 = &hcol[u]
    add  a4, t0, t3          # a4 = &hcol[v]
    la   t0, fcol
    add  a5, t0, t1          # a5 = &fcol[u]
    add  a6, t0, t3          # a6 = &fcol[v]
    la   a7, rowv

    li   t6, 0               # component i = 0, 1, 2
dc_comp:
    slli t0, t6, 2
    add  t1, a2, t0
    lw   t1, 0(t1)           # hcol[a][i]
    bgtz s7, dc_side_pos
    neg  t1, t1
dc_side_pos:
    beqz t6, dc_cx
    li   t2, 1
    beq  t6, t2, dc_cy
    add  t1, t1, s5          # + C[i]
    j    dc_cdone
dc_cx:
    add  t1, t1, s3
    j    dc_cdone
dc_cy:
    add  t1, t1, s4
dc_cdone:
    add  t2, a3, t0
    lw   t2, 0(t2)
    sub  t1, t1, t2          # - hcol[u][i]
    add  t2, a4, t0
    lw   t2, 0(t2)
    sub  t1, t1, t2          # - hcol[v][i]: corner O[i]
    add  t2, a5, t0
    lw   t2, 0(t2)
    srai t2, t2, 3           # d1[i] = fcol[u][i] / 8
    add  t3, a6, t0
    lw   t3, 0(t3)
    srai t3, t3, 3           # d2[i] = fcol[v][i] / 8
    srai t4, t2, 1
    add  t1, t1, t4
    srai t4, t3, 1
    add  t1, t1, t4          # O[i] + d1[i]/2 + d2[i]/2
    add  t4, a7, t0
    sw   t1, 0(t4)           # rowv[i] = first sample (world)
    sw   t3, 12(t4)          # rowv[3 + i] = d2[i]
    beqz t6, dc_dux
    li   t4, 1
    beq  t6, t4, dc_duy
    mv   s11, t2             # duz (kept in s11, then a4)
    j    dc_dnext
dc_dux:
    mv   s8, t2              # dux (kept in s8, then a2)
    j    dc_dnext
dc_duy:
    mv   a1, t2              # duy
dc_dnext:
    addi t6, t6, 1
    li   t4, 3
    bne  t6, t4, dc_comp

    lw   t0, 0(a7)           # world -> screen: x = CX + x, y = CY - y
    li   t1, CX
    add  t0, t0, t1
    sw   t0, 0(a7)
    lw   t0, 4(a7)
    li   t1, CY
    sub  t0, t1, t0
    sw   t0, 4(a7)
    mv   a2, s8              # a2 = dux, a3 = duy, a4 = duz
    mv   a3, a1
    mv   a4, s11

    add  t0, s1, s6          # colour: sticker if this face is on the outside
    lb   t0, 0(t0)
    li   s8, 0
    bne  t0, s7, dc_col_done
    la   t0, pos_slot
    slli t1, s0, 1
    add  t1, t1, s0
    add  t0, t0, t1
    add  t0, t0, s6
    lbu  t0, 0(t0)           # slot of axis a at position p
    add  t0, t0, t1          # p * 3 + slot
    slli t0, t0, 2
    la   t1, colors
    add  t0, t1, t0
    lw   s8, 0(t0)
dc_col_done:
    la   a7, fbz
    li   a6, 8               # rows
dc_row:
    la   t3, rowv
    lw   t0, 0(t3)           # x, y, z of the row start
    lw   t1, 4(t3)
    lw   t2, 8(t3)
    li   a5, 8               # samples in the row
dc_px:
    srai t3, t0, 8           # pixel x
    srai t4, t1, 8           # pixel y
    bltz t3, dc_skip
    li   t5, 35
    bge  t3, t5, dc_skip
    bltz t4, dc_skip
    li   t5, 25
    bge  t4, t5, dc_skip
    slli t5, t4, 5           # k = y * 35 + x
    slli t6, t4, 1
    add  t5, t5, t6
    add  t5, t5, t4
    add  t5, t5, t3
    slli t5, t5, 3
    add  t5, a7, t5          # &fbz[k]
    lw   t6, 4(t5)
    bge  t6, t2, dc_skip     # an earlier sample is at least as near
    sw   t2, 4(t5)
    sw   s8, 0(t5)
dc_skip:
    add  t0, t0, a2
    sub  t1, t1, a3
    add  t2, t2, a4
    addi a5, a5, -1
    bnez a5, dc_px
    la   t3, rowv            # next row: start += d2 (screen y grows downwards)
    lw   t0, 0(t3)
    lw   t4, 12(t3)
    add  t0, t0, t4
    sw   t0, 0(t3)
    lw   t0, 4(t3)
    lw   t4, 16(t3)
    sub  t0, t0, t4
    sw   t0, 4(t3)
    lw   t0, 8(t3)
    lw   t4, 20(t3)
    add  t0, t0, t4
    sw   t0, 8(t3)
    addi a6, a6, -1
    bnez a6, dc_row

dc_side_next:
    li   t0, 1
    bne  s7, t0, dc_axis_next
    li   s7, -1
    j    dc_side
dc_axis_next:
    addi s6, s6, 1
    li   t0, 3
    bne  s6, t0, dc_axis

    addi s0, s0, 1           # next cubie
    addi s1, s1, 3
    li   t0, 8
    bne  s0, t0, dc_cubie

    li   t0, LED_MATRIX_0_BASE   # show the finished frame
    la   t1, fbz
    li   t2, 875
dc_copy:
    lw   t3, 0(t1)
    sw   t3, 0(t0)
    addi t0, t0, 4
    addi t1, t1, 8
    addi t2, t2, -1
    bnez t2, dc_copy

    lw   ra, 0(sp)
    lw   s0, 4(sp)
    lw   s1, 8(sp)
    lw   s2, 12(sp)
    lw   s3, 16(sp)
    lw   s4, 20(sp)
    lw   s5, 24(sp)
    lw   s6, 28(sp)
    lw   s7, 32(sp)
    lw   s8, 36(sp)
    lw   s9, 40(sp)
    lw   s10, 44(sp)
    lw   s11, 48(sp)
    addi sp, sp, 52
    ret
