# Generated by render/gen_render.py: rendering tables.
# Slot k of corner position i shows sticker (k - o) mod 3 of the cubie there,
# where o is its orientation; this order matches solver.c's twist table.
    .data
    .align 2
cubie_color:                 # [cubie 0..7][slot 0..2] RGB of each sticker when solved
    .word 0xFFFFFF, 0xFF8000, 0x00B000
    .word 0xFFFFFF, 0x00B000, 0xE00000
    .word 0xFFD700, 0xE00000, 0x00B000
    .word 0xFFD700, 0x00B000, 0xFF8000
    .word 0xFFFFFF, 0xE00000, 0x0040FF
    .word 0xFFD700, 0x0040FF, 0xE00000
    .word 0xFFD700, 0xFF8000, 0x0040FF
    .word 0xFFFFFF, 0x0040FF, 0xFF8000
pos_offset:                  # [position 0..7][slot 0..2] LED byte offset of the facelet's top-left pixel
    .half 736, 1276, 1296
    .half 752, 1312, 1332
    .half 2292, 1752, 1732
    .half 2276, 1716, 1696
    .half 332, 1348, 1368
    .half 2712, 1788, 1768
    .half 2696, 1680, 1804
    .half 316, 1384, 1260
move_source:                 # solver.c source[face][dest]
    .byte 1, 4, 2, 0, 3, 5, 6
    .byte 0, 1, 2, 4, 5, 6, 3
    .byte 0, 2, 5, 3, 1, 4, 6
move_twist:                  # solver.c twist[face][dest]
    .byte 1, 2, 0, 2, 1, 0, 0
    .byte 0, 0, 0, 1, 2, 1, 2
    .byte 0, 0, 0, 0, 0, 0, 0
move_face:                   # move 0..8 -> face 0..2
    .byte 0, 0, 0, 1, 1, 1, 2, 2, 2
move_turns:                  # move 0..8 -> number of quarter turns
    .byte 1, 2, 3, 1, 2, 3, 1, 2, 3
    .align 2

# Cube state for rendering: the same 14-character encoding as the input,
# as numbers (positions 1..7: cubie 0..6, orientation 0..2).
cube_p:
    .zero 8
cube_o:
    .zero 8
tmp_p:
    .zero 8
tmp_o:
    .zero 8
# dump_frame (CLI check only): colour -> letter
dump_colors:
    .word 0x000000, 0xFFFFFF, 0xFFD700, 0x00B000, 0x0040FF, 0xE00000, 0xFF8000
dump_letters:
    .byte 46, 87, 89, 71, 66, 82, 79, 63     # . W Y G B R O ?
    .align 2

    .text
# ---------------------------------------------------------------------------
# parse_cube: a0 = address of the 14-character state -> cube_p, cube_o
# ---------------------------------------------------------------------------
parse_cube:
    la   t0, cube_p
    la   t1, cube_o
    li   t2, 0
pc_loop:
    add  t3, a0, t2
    lbu  t4, 0(t3)           # position digit '1'..'7'
    addi t4, t4, -49
    add  t5, t0, t2
    sb   t4, 0(t5)
    lbu  t4, 7(t3)           # orientation digit '1'..'3'
    addi t4, t4, -49
    add  t5, t1, t2
    sb   t4, 0(t5)
    addi t2, t2, 1
    li   t3, 7
    bne  t2, t3, pc_loop
    ret

# ---------------------------------------------------------------------------
# apply_move: a0 = move 0..8. Applies it to cube_p / cube_o with the same
# source and twist tables as solver.c's quarter_turn, once per quarter turn.
# Uses t0-t5, a1-a7.
# ---------------------------------------------------------------------------
apply_move:
    la   t0, move_face
    add  t0, t0, a0
    lbu  t1, 0(t0)           # face
    la   t0, move_turns
    add  t0, t0, a0
    lbu  t2, 0(t0)           # quarter turns: 1, 2 or 3
    slli t3, t1, 3           # face * 7 = (face << 3) - face
    sub  t3, t3, t1
    la   t4, move_twist
    add  t4, t4, t3          # t4 = twist[face]
    la   t5, move_source
    add  t3, t5, t3          # t3 = source[face]
am_turn:
    la   a1, cube_p
    la   a2, cube_o
    la   a3, tmp_p
    la   a4, tmp_o
    li   t5, 0               # dest i
am_i:
    add  a5, t3, t5
    lbu  a5, 0(a5)           # s = source[face][i]
    add  a6, a1, a5
    lbu  a6, 0(a6)
    add  a7, a3, t5
    sb   a6, 0(a7)           # tmp_p[i] = cube_p[s]
    add  a6, a2, a5
    lbu  a6, 0(a6)
    add  a7, t4, t5
    lbu  a7, 0(a7)
    add  a6, a6, a7          # cube_o[s] + twist[face][i], at most 4
    li   a7, 3
    blt  a6, a7, am_mod
    addi a6, a6, -3          # mod 3
am_mod:
    add  a7, a4, t5
    sb   a6, 0(a7)           # tmp_o[i]
    addi t5, t5, 1
    li   a7, 7
    bne  t5, a7, am_i
    li   t5, 0
am_copy:
    add  a5, a3, t5
    lbu  a6, 0(a5)
    add  a5, a1, t5
    sb   a6, 0(a5)
    add  a5, a4, t5
    lbu  a6, 0(a5)
    add  a5, a2, t5
    sb   a6, 0(a5)
    addi t5, t5, 1
    li   a7, 7
    bne  t5, a7, am_copy
    addi t2, t2, -1
    bnez t2, am_turn
    ret

# ---------------------------------------------------------------------------
# render_cube: draw the net of cube_p / cube_o on the LED matrix.
# The LED matrix is row-major: pixel (x, y) is at BASE + (y * 35 + x) * 4.
# Each facelet is 4 x 3 pixels: 12 stores at offsets 0..12, +140, +280.
# Uses t0-t5, a0-a7.
# ---------------------------------------------------------------------------
render_cube:
    li   t0, LED_MATRIX_0_BASE
    la   t1, pos_offset      # walks the table: position-major, slot-minor
    la   t2, cubie_color
    la   t3, cube_p
    la   t4, cube_o
    li   t5, 0               # position i = 0..7
rc_pos:
    beqz t5, rc_anchor
    add  a0, t3, t5
    lbu  a1, -1(a0)          # cubie at position i (0..6) ...
    addi a1, a1, 1           # ... numbered 1..7; cubie 0 is the fixed anchor
    add  a0, t4, t5
    lbu  a2, -1(a0)          # its orientation
    j    rc_have
rc_anchor:
    li   a1, 0               # position 0 always holds cubie 0, orientation 0
    li   a2, 0
rc_have:
    slli a3, a1, 3           # a3 = &cubie_color[c][0] = cubie_color + 12 * c
    slli a4, a1, 2
    add  a3, a3, a4
    add  a3, t2, a3
    li   a4, 0               # slot k = 0..2
rc_slot:
    sub  a5, a4, a2          # sticker j = (k - o) mod 3
    bgez a5, rc_j
    addi a5, a5, 3
rc_j:
    slli a5, a5, 2
    add  a5, a3, a5
    lw   a6, 0(a5)           # colour
    lhu  a7, 0(t1)           # LED offset of this facelet
    addi t1, t1, 2
    add  a7, t0, a7
    sw   a6, 0(a7)           # row 0
    sw   a6, 4(a7)
    sw   a6, 8(a7)
    sw   a6, 12(a7)
    sw   a6, 140(a7)         # row 1: one LED row is 35 * 4 = 140 bytes
    sw   a6, 144(a7)
    sw   a6, 148(a7)
    sw   a6, 152(a7)
    sw   a6, 280(a7)         # row 2
    sw   a6, 284(a7)
    sw   a6, 288(a7)
    sw   a6, 292(a7)
    addi a4, a4, 1
    li   a5, 3
    bne  a4, a5, rc_slot
    addi t5, t5, 1
    li   a5, 8
    bne  t5, a5, rc_pos
    ret

# ---------------------------------------------------------------------------
# dump_frame (CLI check build only): print the LED memory as 25 lines of
# 35 letters, one per pixel.
# ---------------------------------------------------------------------------
dump_frame:
    li   t0, LED_MATRIX_0_BASE
    li   t1, 0               # x
    li   t2, 875             # pixels left
df_pixel:
    lw   t3, 0(t0)
    la   t4, dump_colors
    la   t5, dump_letters
    li   a1, 7
df_find:
    lw   a2, 0(t4)
    beq  a2, t3, df_found
    addi t4, t4, 4
    addi t5, t5, 1
    addi a1, a1, -1
    bnez a1, df_find
df_found:
    lbu  a0, 0(t5)           # matching letter, or '?' after the last colour
    li   a7, 11
    ecall
    addi t0, t0, 4
    addi t1, t1, 1
    li   a2, 35
    bne  t1, a2, df_next
    li   t1, 0
    li   a0, 10
    ecall
df_next:
    addi t2, t2, -1
    bnez t2, df_pixel
    li   a0, 10
    ecall
    ret

# ---------------------------------------------------------------------------
# delay: busy loop of FRAME_DELAY iterations so each frame stays visible.
# ---------------------------------------------------------------------------
delay:
    li   t0, FRAME_DELAY
    beqz t0, dl_end
dl_loop:
    addi t0, t0, -1
    bnez t0, dl_loop
dl_end:
    ret
