import os
exec(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'model.py')).read().split("# 1) check permutation")[0])
def sticker_dir(p,ax):
    c=POS[p]; v=[0,0,0]; v[ax]=c[ax]; return tuple(v)
def cyc(p):
    a=sticker_dir(p,1); b=sticker_dir(p,2); cc=sticker_dir(p,0)
    det=a[0]*(b[1]*cc[2]-b[2]*cc[1])-a[1]*(b[0]*cc[2]-b[2]*cc[0])+a[2]*(b[0]*cc[1]-b[1]*cc[0])
    o=[1,2,0] if det<0 else [1,0,2]
    return [o[0],o[2],o[1]]          # the order verified against the twist table
W=35
FACE_ORIGIN={'U':(9,2),'L':(0,9),'F':(9,9),'R':(18,9),'B':(27,9),'D':(9,16)}
def face_of(ax,sign): return {(0,1):'R',(0,-1):'L',(1,1):'U',(1,-1):'D',(2,1):'F',(2,-1):'B'}[(ax,sign)]
def cell(face,c):     # (col,row) of a corner's sticker on its face, as seen in the net
    x,y,z=c
    if face=='F': return (0 if x<0 else 1, 0 if y>0 else 1)
    if face=='R': return (0 if z>0 else 1, 0 if y>0 else 1)
    if face=='B': return (0 if x>0 else 1, 0 if y>0 else 1)
    if face=='L': return (0 if z<0 else 1, 0 if y>0 else 1)
    if face=='U': return (0 if x<0 else 1, 0 if z<0 else 1)
    if face=='D': return (0 if x<0 else 1, 0 if z>0 else 1)
COLOR={'U':0xFFFFFF,'D':0xFFD700,'F':0x00B000,'B':0x0040FF,'R':0xE00000,'L':0xFF8000}
LETTER={'U':'W','D':'Y','F':'G','B':'B','R':'R','L':'O'}
pos_off=[];cub_col=[]
for p in range(8):
    for ax in cyc(p):
        c=POS[p]; f=face_of(ax,c[ax]); col,row=cell(f,c); ox,oy=FACE_ORIGIN[f]
        x=ox+4*col; y=oy+3*row
        pos_off.append((y*W+x)*4)
        cub_col.append(COLOR[f])
out=[]
out.append("# Generated by render/gen_render.py: rendering tables.")
out.append("# Slot k of corner position i shows sticker (k - o) mod 3 of the cubie there,")
out.append("# where o is its orientation; this order matches solver.c's twist table.")
out.append("    .data")
out.append("    .align 2")
out.append("cubie_color:                 # [cubie 0..7][slot 0..2] RGB of each sticker when solved")
for p in range(8): out.append("    .word " + ", ".join("0x%06X"%cub_col[p*3+k] for k in range(3)))
out.append("pos_offset:                  # [position 0..7][slot 0..2] LED byte offset of the facelet's top-left pixel")
for p in range(8): out.append("    .half " + ", ".join(str(pos_off[p*3+k]) for k in range(3)))
out.append("move_source:                 # solver.c source[face][dest]")
for f in range(3): out.append("    .byte " + ", ".join(map(str,source[f])))
out.append("move_twist:                  # solver.c twist[face][dest]")
for f in range(3): out.append("    .byte " + ", ".join(map(str,twist[f])))
out.append("move_face:                   # move 0..8 -> face 0..2")
out.append("    .byte 0, 0, 0, 1, 1, 1, 2, 2, 2")
out.append("move_turns:                  # move 0..8 -> number of quarter turns")
out.append("    .byte 1, 2, 3, 1, 2, 3, 1, 2, 3")
out.append("    .align 2")
open(os.path.join(os.path.dirname(os.path.abspath(__file__)),'render_data.s'),'w').write("\n".join(out)+"\n")
# python reference: ASCII frame for a state, using LED layout
import json

